### ISSUE TITLE
 源码版本设定最好加上

### ISSUE THREAD

**Issue by fdcmessenger** [yiyongfei/yea#1]
clone下来进行尝试时发现两个小小的问题

1. 源码中有1.5不认识的语法，最好在plugin中加上关于源码版本的设定内容
2. init.sql的前两行的注释在运行时报错，发现可能是少了空格造成的。
请确认。

另外看了看源码感觉还是挺有针对性的，是从实践中得来的。加油。

**Comment by yiyongfei** [comment]
谢谢关注，已修复
